### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [lucianodato/libspecbleach#26]
The 'install' target is typically expected to install the files.

**Comment by lucianodato** [comment]
Thanks! yeah! I'm fixing it right now! Sorry for the inconvenience

**Comment by yurivict** [comment]
No problem!

Now it installs the shared library, but not the headers.

**Comment by lucianodato** [comment]
Yeah sorry about that! Latest release should do it! But I leave this open until you confirm is fixed

**Comment by yurivict** [comment]
It is ok now, thanks!
