### ISSUE TITLE
Memory issue, Windows

### ISSUE THREAD

**Issue by SimonG4ELI** [lucianodato/libspecbleach#34]
I have compiled this in a 64-Bit Windows MFC DLL, works superbly but I believe the heap is being corrupted. I am so impressed with libspecbleach that I'm spending considerable time trying to try this down. Available via e-mail as simon@sdr-radio.com .

**Comment by SimonG4ELI** [comment]
Same problem with 32-bit. My audio sample rates are 8k and 24k. I can initialise then free, that is OK, But if I initialise, run then free my heap is corrupted.

**Comment by SimonG4ELI** [comment]
Quick update - this seems to depend on the sample rate. Using 48,000 and the heap isn't corrupted, 8k, 12k, 24k and it is.

**Comment by SimonG4ELI** [comment]
FWIW this may be my code, I'll let you know if I can't fix it.

**Comment by lucianodato** [comment]
Hey Simon! Many thanks for your input. The issue has been reported already. I'm dealing with it as fas as I can. Checkout the dev branch if you are interested in the latest changes. Also as you remarked in the other issue let me know if any code documentation is not clear. This is my first c lib so no expert here.

**Comment by SimonG4ELI** [comment]
Ah - I thought I had seen a reference to a memory issue but couldn't find it. I'll check the dev branch later today.

**Comment by lucianodato** [comment]
Hey Simon! Sorry for the long delay but I think I've got it now. Would you mind testing current master? Also I've written better explanation on the header file for the parameters. Let me know if that clarifies your questions.

**Comment by SimonG4ELI** [comment]
Hi,

Thanks - will test early tomorrow morning and let you know.

**Comment by SimonG4ELI** [comment]
Hi,

No - the processing in **specbleach_adaptive_process()** is corrupting the heap somewhere. This doesn't cause a crash, but the heap check when running in debug mode generates diagnostics. I'll maybe step through the code myself, it could also be a Windows thing with the compilation.

The noise reduction is excellent.

**Comment by lucianodato** [comment]
You are right and actually looking at my meson command in my tasks I found that I had not enable all warnings and from what I've looked quickly there's some stuff that I need to fix. No need to dig the code. I'll let you know soon.

**Comment by SimonG4ELI** [comment]
OK, great. I'll get a video on my website today showing your code cleaning up shortwave transmissions.

**Comment by SimonG4ELI** [comment]
So,

What I'll do in a few days is add diagnostics and bound checks:

- When freeing a pointer I always set the pointer to null (0) so it doesn't get freed twice.
- In debug mode check array bounds when accessing data, using assert().

The above will find the problem.

**Comment by SimonG4ELI** [comment]
So,

What I'll do in a few days is add diagnostics and bound checks:
- When freeing a pointer I always set the pointer to null (0) so it doesn't get freed twice
- In debug mode check array bounds when accessing data.

**Comment by lucianodato** [comment]
Ok so the issue is basically that whenever you use different samplerates that are less than 20k in their nyquist the critical bands are trying to use the full spectrum which is not available. My bad in not testing with lowersample rates. I'm going to include some heuristics to consider these special cases. Sorry for all the trouble and thanks for the help!! Will keep you posted here,,,

**Comment by SimonG4ELI** [comment]
Hi,

I can always resample to 48k but would appreciate some work for 8k sample rates as this is the one I use most. As this is live audio I'm always running adaptively. Anything you can do is really appreciated, many thanks for this excellent software.

**Comment by lucianodato** [comment]
> Hi,
> 
> I can always resample to 48k but would appreciate some work for 8k sample rates as this is the one I use most. As this is live audio I'm always running adaptively. Anything you can do is really appreciated, many thanks for this excellent software.

Not at all actually this is not a big deal to fix. I think I've already got it. It is uploaded to the development branch if you want to give it a quick test. I'm very glad that you find it useful to you.

**Comment by lucianodato** [comment]
I've tried 8k, 16k, 44.1k, 48k and 96k and all seem to be working but let me know your findings

**Comment by SimonG4ELI** [comment]
> I've tried 8k, 16k, 44.1k, 48k and 96k and all seem to be working but let me know your findings

Looks good, no problem with my sample rates.

**Comment by lucianodato** [comment]
Should I mark this as resolved and do a bug fix release?

**Comment by SimonG4ELI** [comment]
Yes, works 100%
