### ISSUE TITLE
Use of inline

### ISSUE THREAD

**Issue by SimonG4ELI** [lucianodato/libspecbleach#39]
Hi,

I'm using this library in a 64-bit Windows DLL with Visual Studio 2019, the DLL is a mix of C++ (my code) and C (LibSpecBleach).

The use of inline in **general_utils.c** and **spectral_utils.c** results in the functions not being available - the compiler removes them. A good C compiler will inline all suitable functions anyway.

Would it be possible to remove the use of inline? Every time I use a new download from here I have to edit these two files.

**Comment by lucianodato** [comment]
Absolutely! In fact I forgot to do it when moving that code from noise repellent. Will do shortly!

**Comment by lucianodato** [comment]
Ok I've uploaded some fixes on dev. Off to work but I'll continue in the afternoon
