### ISSUE TITLE
Whitening factor in adaptive denoising?

### ISSUE THREAD

**Issue by Yahweasel** [lucianodato/libspecbleach#50]
Apologies if this is just a case of me not understanding the core technology, but why isn't whitening factor exported as part of the adaptive denoising API, when it is part of the learning denoising API? Coming from noise-repellent, and unless I'm a loony, whitening definitely worked just as well in adaptive mode there as in learning mode.

**Comment by lucianodato** [comment]
I removed it specifically because with recent changes it was acting weirdly. The last thing I was doing it was actually to expose more functionality in the api so that's coming. I'll get back to develop this coming winter hopefully.

**Comment by lucianodato** [comment]
Added. Will be released in the next stable release

**Comment by Yahweasel** [comment]
Fantastic, thanks!
