### ISSUE TITLE
Noise modeling options

### ISSUE THREAD

**Issue by lucianodato** [lucianodato/libspecbleach#8]
Give the user the possibility of using the rolling mean or max functions for noise spectrum modeling

**Comment by lucianodato** [comment]
Related to #43

**Comment by lucianodato** [comment]
Add moving median option with k 3

**Comment by lucianodato** [comment]
Got this results till now:

Moving Average profile (current behavior):
![image](https://user-images.githubusercontent.com/1414264/171056895-37e42892-f0fb-4bd0-8c39-866f2b1ae598.png)

Moving Max-Median profile:
![image](https://user-images.githubusercontent.com/1414264/171056959-7cc0baaa-bde3-45a7-8586-66a7ab6c7045.png)

Max profile:
![image](https://user-images.githubusercontent.com/1414264/171057025-566d34e1-1c23-46ce-bbc3-796cca1e7dd6.png)

Clearly these go up in aggressiveness so the choice will be available for the user to choose in their specific case through the API.

**Comment by SimonG4ELI** [comment]
Looks superb!
